### PR TITLE
add remotes and update imports

### PR DESCRIPTION
**Pull request by luca-dex**
This allow the package to be installed directly with `install_github("caravagn/mobster")` without having to install `Pio` and `easypar` in advance.

In addition the package `clisymbols` has been added to `NAMESPACE`.

### CODE REVIEW

**Comment by caravagn** [comment]
Thanks, I am in the middle of pushing some commit that was actually changing the DESCRIPTION file as well. I think this package has too many dependencies and wanted to find a way to lift some of them. I think it fails on travis also because of this (takes too much time to build up the R env).

**Comment by marcjwilliams1** [comment]
@caravagn I played around with using github actions rather than travis for CI yesterday. You can see it on this branch: https://github.com/caravagn/mobster/tree/tests in case it's useful.

Github actions allows for longer runtime but it is also failing, I think it's because R CMD CHECK only allows CRAN packages as dependencies and will error otherwise.

**Comment by luca-dex** [comment]
Ciao @marcjwilliams1 , despite the errors still present on travis, due to some problem in the vignette, the objective of these commits was to fix the installation process.

Now, if you execute `install_github("caravagn/mobster", ref="development")` you should be able to install mobster on any platform. There is still some warning, but these are easy to fix.

**Comment by caravagn** [comment]
I think we have already discussed this no? What is left to do here? I have just done some push to development and I am gonna trigger now a pull req dev to master

**Pull request merged**
