### PR TITLE
Force this?

### PR DESCRIPTION
**Pull request by caravagn**
@luca-dex shall we do this (cancelling last commit) or create a new dev?

### CODE REVIEW

**Comment by luca-dex** [comment]
Naaaa, just destroy the dev branch and then recreate it from master

**Comment by caravagn** [comment]
Why did vignette fail in the action?

**Comment by luca-dex** [comment]
Because you use phantomjs which is now deprecated. Do you think it is
possible to remove it and use something else? It's used by webshot

**Comment by caravagn** [comment]
Can you point me where this is used? I never heard of that. A quick grep of `phantomjs` in the source files does not find anything...

**Comment by luca-dex** [comment]
It is used by webshot.. it is an executable that you need to have in your
path for all the OS.
Somewhere you call a function from the webshot package that needs this
phantomjs and if it is not installed ask you to install it...

During this action:
##[error]--- re-building ‘a1_introduction.Rmd’ using rmarkdown

I get this error:
PhantomJS not found. You can install it with webshot::install_phantomjs().
If it is installed, please make sure the phantomjs executable can be found
via the PATH variable.

And also this:

##[error]Error: processing vignette 'a2_plotting.Rmd' failed with
diagnostics:
Functions that produce HTML output found in document targeting gfm output.
Please change the output type of this document to HTML. Alternatively, you
can allow
HTML output in non-HTML formats by adding this option to the YAML
front-matter of
your rmarkdown file:
always_allow_html: true
Note however that the HTML output will not be visible in non-HTML formats.

**Comment by caravagn** [comment]
Ok those vignettes show many functions, can we boil it down to the one/two/... using `webshot`?

**Comment by caravagn** [comment]
Again no explicit call to webshot is there...

**Comment by luca-dex** [comment]
I found this:

If you include an HTML widget in a non-HTML output format, such as a PDF,
*knitr* will try to embed a screenshot of the widget if you have installed
the R package *webshot* (Chang 2019
<https://bookdown.org/yihui/rmarkdown/interactive-documents.html#ref-R-webshot>
) and the PhantomJS package (via webshot::install_phantomjs()).

From

   - https://bookdown.org/yihui/rmarkdown/interactive-documents.html
   - https://bookdown.org/yihui/bookdown/html-widgets.html


And probably it is related to the usage of plotly...

https://stackoverflow.com/questions/33998996/exporting-png-files-from-plotly-in-r-without-internet

**Pull request merged**
